server:
  port: 8000
spring:
  application:
    name: auth
  redis:
    database: 1
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789

eureka:
  instance:
    instance-id: auth
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/example/auth/mapper/*.xml
  global-config:
    banner: false

